#Simple workflow for github Actions.

name: Chuck Norris Joke app push CI

on:
  push:
    branches: [ main ]

# Jobs for unit tests, APK upload to artifacts.
jobs:
  test:
    name: Run Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: ./gradlew test --stacktrace

  build_apk:
    name: Upload APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug APK
        run: |
            sudo chmod +x ./gradlew
                          ./gradlew :app:packageDebugUniversalApk --stacktrace

      - name: Upload to artifacts
        uses: actions/upload-artifact@v2

        with:
          name: app
          path: app/build/outputs/universal_apk/debug/app-debug-universal.apk

      - name: Create release
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.1
          asset_path: app/build/outputs/universal_apk/debug/app-debug-universal.apk
          asset_name: chuck_norris_joke_debug.apk
          asset_content_type: application/zip
